### ISSUE TITLE
Ip ban when using ‘create_depth_cache’ with many symbols

### ISSUE THREAD

**Issue by mrandybu** [LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache#30]
### Is your feature request related to a problem? Please describe.

When passing list with many symbols in create_depth_cache method we getting ip ban, because ubldc sent rest to binance by each symbol.

**Comment by taekop** [comment]
I think a good way to handle a lot of symbols is to call 'create_depth_cache' slowly for each market, say 60 markets per minute.

```python
for market in markets:
    time.sleep(1)
    ubldc.create_depth_cache(markets=market)
```

Unfortunately, because markets are added during the iteration, error is often raised.

```
RuntimeError: dictionary changed size during iteration
```

https://github.com/LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache/blob/c61d111dc4c252cdd5fbb272e70b6b8c5d2393b2/unicorn_binance_local_depth_cache/manager.py#L467

**Comment by oliver-zehentleitner** [comment]
i will include a solution that takes the current weight cost into account and simply does not exceed it. this way the coder does not have to pay attention to it anymore and no fixed delays are necessary. Due to a restructuring at LUCIT I will not be able to provide an update until the end of July.

**Comment by oliver-zehentleitner** [comment]
Will be rolled out on Monday

**Comment by oliver-zehentleitner** [comment]
I have noticed in tests that the current architecture with many caches does not scale well. For example, we use one WebSocket connection per cache. This may be good for a few caches, but not for many. I will rewrite some things and then publish an update. But I don't think I'll be able to do that before Christmas.

**Comment by oliver-zehentleitner** [comment]
Will be fixed in the next release.

**Comment by oliver-zehentleitner** [comment]
2.0.0 has been released https://pypi.org/project/unicorn-binance-local-depth-cache/
